### PR TITLE
[rfc] key design

### PR DESCRIPTION
**Pull request by xzhangxian1008**
The design document for metable to map the table data to kv storage.

### CODE REVIEW

**Comment by jovany-wang** [comment]
A good PR. But I saw it's an investigation on F1, TiDB and etc. Could you add your designing for Metable? like:

# 1. Invesitgations
## F1
XXX
## TiDB
xxx

# 2. Metable Design

**Comment by jovany-wang** [comment]
A good PR. But I saw it's an investigation on F1, TiDB and etc. Could you add your designing for Metable? like:

# 1. Invesitgations
## F1
XXX
## TiDB
xxx

# 2. Metable Design

**Comment by jovany-wang** [comment]
The next step for this PR is to make the proposal for Metable data -> kv mapping.

**Comment by xzhangxian1008** [comment]
> The next step for this PR is to make the proposal for Metable data -> kv mapping.

ok

**Comment by jovany-wang** [comment]
Is there any update?

**Comment by xzhangxian1008** [comment]
> Is there any update?

I'm dealing with graduation recently, I will update it as soon as possible.

**Pull request closed without merging**
